---
- name: Criar ~/.docker para cada usuário
  file:
    path: "{{ item.home }}/.docker"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0700'
  loop: "{{ existing_docker_users_info }}"

- name: Copiar cert.pem para cada usuário
  copy:
    src: "{{ docker_cert_dir }}/cert.pem"
    dest: "{{ item.home }}/.docker/cert.pem"
    remote_src: yes
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0600'
  loop: "{{ existing_docker_users_info }}"

- name: Copiar key.pem para cada usuário
  copy:
    src: "{{ docker_cert_dir }}/key.pem"
    dest: "{{ item.home }}/.docker/key.pem"
    remote_src: yes
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0600'
  loop: "{{ existing_docker_users_info }}"

- name: Copiar ca.pem para cada usuário
  copy:
    src: "{{ docker_cert_dir }}/ca.pem"
    dest: "{{ item.home }}/.docker/ca.pem"
    remote_src: yes
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0600'
  loop: "{{ existing_docker_users_info }}"

- name: Definir variável DOCKER_HOST em .bashrc para cada usuário
  lineinfile:
    path: "{{ item.home }}/.bashrc"
    line: 'export DOCKER_HOST=tcp://127.0.0.1:2376 DOCKER_TLS_VERIFY=1'
    create: yes
    state: present
    insertafter: EOF
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0644'
  loop: "{{ existing_docker_users_info }}"
