---
- name: Detect docker-users (ID >= 999)
  import_tasks: docker-users.yml

- name: Variables to install and configure Docker with TLS support
  debug:
    msg: 
      - "inventory_hostname: {{ inventory_hostname }}"
      - "docker_users: {{ docker_users }}"
      - "docker_cert_dir: {{ docker_cert_dir }}"
      - "ansible_all_ipv4_addresses: {{ ansible_all_ipv4_addresses }}"
      - "ca_valid_days: {{ ca_valid_days }}"
      - "cert_valid_days: {{ cert_valid_days }}"
      - "cert_bits: {{ cert_bits }}"

- name: Install Docker
  import_role:
    name: geerlingguy.docker

- name: Setup Docker with TLS support - Create X509 certs
  import_tasks: create-x509-certs.yaml

- name: Setup Docker with TLS support - Copy certs to host
  import_tasks: copy-certs-to-host.yml

- name: Setup Docker with TLS support - Configure docker service
  import_tasks: config-docker-service.yml

- name: Setup Docker with TLS support - Configure docker client
  import_tasks: config-docker-client.yml
